name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_artifacts:
    name: Build artifacts

    strategy:
      matrix:
        platform:
          - runner_os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            archive_prefix: workbench-linux-aarch64

          - runner_os: macos-latest
            target: aarch64-apple-darwin
            archive_prefix: workbench-macos-aarch64

          - runner_os: ubuntu-latest
            target: i686-unknown-linux-gnu
            archive_prefix: workbench-linux-i686

          - runner_os: windows-latest
            target: i686-pc-windows-msvc
            archive_prefix: workbench-windows-i686

          - runner_os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive_prefix: workbench-linux-x86_64

          - runner_os: macos-latest
            target: x86_64-apple-darwin
            archive_prefix: workbench-macos-x86_64

          - runner_os: windows-latest
            target: x86_64-pc-windows-msvc
            archive_prefix: workbench-windows-x86_64

    runs-on: ${{ matrix.platform.runner_os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release
        run: cross build --release --target ${{ matrix.platform.target }}

      - name: Test release
        run: cross test --release --target ${{ matrix.platform.target }}

      # - name: Create a release in GitHub
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
