name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_artifacts:
    name: Build artifacts for ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            runner_os: ubuntu-latest
          - target: aarch64-apple-darwin
            runner_os: macos-latest
          - target: x86_64-unknown-linux-gnu
            runner_os: ubuntu-latest
          - target: x86_64-apple-darwin
            runner_os: macos-latest
          - target: x86_64-pc-windows-msvc
            runner_os: windows-latest
          - target: i686-unknown-linux-gnu
            runner_os: ubuntu-latest
          - target: i686-pc-windows-msvc
            runner_os: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build artifact
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: --release
          strip: true

      # - name: Create a release in GitHub
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
