name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cargo build

      - run: cargo clippy

      - run: cargo test

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
